version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/tools/discrawl-ja"
      - "/tools/discrawl-kiwi"
      - "/tools/discrawl-zh"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
